	# Setar a imagem base como Ubuntu
FROM redis:8.4.0-bookworm

	# Autor/Mantenedor
MAINTAINER Jonathan Baraldi

	# Atualizar o repositório e instalar o server do Redis
# RUN apt-get update && apt-get install -y redis-server

	# Expor Redis na porta 6379
EXPOSE 6379

	# Rodar Redis Server
# ENTRYPOINT  ["/usr/bin/redis-server"]